package br.com.barbershop.view;

import br.com.barbershop.controller.ExcluirClienteController;
import javax.swing.JComboBox;

public class ExcluirCliente extends javax.swing.JFrame {

    private final ExcluirClienteController controller;
    
    public ExcluirCliente() {
        initComponents();
        controller = new ExcluirClienteController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExcluir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jComboBoxExcluirCliente = new javax.swing.JComboBox<>();
        jLabelExcluirCliente = new javax.swing.JLabel();
        jLabelFundoPainel = new javax.swing.JLabel();
        jLabelFundoExclusaoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExcluir.setBackground(new java.awt.Color(0, 204, 51));
        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 160, 30));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        jComboBoxExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxExcluirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 260, 30));

        jLabelExcluirCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelExcluirCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExcluirCliente.setText("Excluir Cliente");
        getContentPane().add(jLabelExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabelFundoPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/painel-login.png"))); // NOI18N
        getContentPane().add(jLabelFundoPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 560, 390));

        jLabelFundoExclusaoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/exclusao-cliente.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoExclusaoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       this.controller.excluirCliente();
       this.controller.restart();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxExcluirClienteActionPerformed
        
    }//GEN-LAST:event_jComboBoxExcluirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JComboBox<String> jComboBoxExcluirCliente;
    private javax.swing.JLabel jLabelExcluirCliente;
    private javax.swing.JLabel jLabelFundoExclusaoCliente;
    private javax.swing.JLabel jLabelFundoPainel;
    private javax.swing.JLabel jLabelNome;
    // End of variables declaration//GEN-END:variables

    public void iniciar(){
         this.controller.atualizaCliente();
    }
    
    public JComboBox<String> getjComboBoxExcluirCliente() {
        return jComboBoxExcluirCliente;
    }

    public void setjComboBoxExcluirCliente(JComboBox<String> jComboBoxExcluirCliente) {
        this.jComboBoxExcluirCliente = jComboBoxExcluirCliente;
    }
    
    
}
