package br.com.barbershop.view;

import br.com.barbershop.controller.ExcluirUsuarioController;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;

public class ExcluirUsuario extends javax.swing.JFrame {

    private final ExcluirUsuarioController controller;
    
    public ExcluirUsuario() {
        initComponents();
        controller = new ExcluirUsuarioController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExcluir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jComboBoxExcluirUsuario = new javax.swing.JComboBox<>();
        jLabelExcluirUsuario = new javax.swing.JLabel();
        jLabelFundoPainel = new javax.swing.JLabel();
        jLabelFundoExclusaoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExcluir.setBackground(new java.awt.Color(0, 204, 51));
        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 160, 30));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        jComboBoxExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxExcluirUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxExcluirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 260, 30));

        jLabelExcluirUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelExcluirUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExcluirUsuario.setText("Excluir Usuário");
        getContentPane().add(jLabelExcluirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabelFundoPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/painel-login.png"))); // NOI18N
        getContentPane().add(jLabelFundoPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 560, 390));

        jLabelFundoExclusaoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/exclusao-usuario.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoExclusaoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonExcluirActionPerformed
       this.controller.excluirUsuario();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxExcluirUsuarioActionPerformed
        
    }//GEN-LAST:event_jComboBoxExcluirUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JComboBox<String> jComboBoxExcluirUsuario;
    private javax.swing.JLabel jLabelExcluirUsuario;
    private javax.swing.JLabel jLabelFundoExclusaoUsuario;
    private javax.swing.JLabel jLabelFundoPainel;
    private javax.swing.JLabel jLabelNome;
    // End of variables declaration//GEN-END:variables

    public void iniciar(){
         try {
			this.controller.atualizaUsuario();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
    }

    public JComboBox<String> getjComboBoxExcluirUsuario() {
        return jComboBoxExcluirUsuario;
    }

    public void setjComboBoxExcluirUsuario(JComboBox<String> jComboBoxExcluirUsuario) {
        this.jComboBoxExcluirUsuario = jComboBoxExcluirUsuario;
    }

    public Object getjComboBoxExcluirCliente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
