package br.com.barbershop.view;

public class Relatorio extends javax.swing.JFrame {
 
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRelatorioVendas = new javax.swing.JButton();
        jButtonRelatorioCliente = new javax.swing.JButton();
        jButtonRelatorioUsuario = new javax.swing.JButton();
        labelFundoRelatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 535));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/relatorio-de-cliente.png"))); // NOI18N
        getContentPane().add(jButtonRelatorioVendas);
        jButtonRelatorioVendas.setBounds(250, 330, 200, 110);

        jButtonRelatorioCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/relatorio-de-usuario.png"))); // NOI18N
        getContentPane().add(jButtonRelatorioCliente);
        jButtonRelatorioCliente.setBounds(250, 170, 200, 120);

        jButtonRelatorioUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRelatorioUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/relatorio-de-venda.png"))); // NOI18N
        getContentPane().add(jButtonRelatorioUsuario);
        jButtonRelatorioUsuario.setBounds(250, 20, 200, 120);

        labelFundoRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/relatorio.jpg"))); // NOI18N
        getContentPane().add(labelFundoRelatorio);
        labelFundoRelatorio.setBounds(0, 0, 750, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioCliente;
    private javax.swing.JButton jButtonRelatorioUsuario;
    private javax.swing.JButton jButtonRelatorioVendas;
    private javax.swing.JLabel labelFundoRelatorio;
    // End of variables declaration//GEN-END:variables
}
