package br.com.barbershop.view.cliente;

import br.com.barbershop.model.Cliente;
import br.com.barbershop.service.ClienteService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author jefferson.silva
 */
public class ExcluirCliente extends javax.swing.JFrame {

    private ClienteService service;
    private DefaultListModel modelo;
    private int enter;
    
public ExcluirCliente() throws SQLException {
    initComponents();
    service = new ClienteService(this);
    modelo = new DefaultListModel(); // Adicione esta linha para inicializar o DefaultListModel
    jListaCliente.setVisible(false);
    jListaCliente.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaCliente = new javax.swing.JList<>();
        jButtonExcluir = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabelFundoExcluirCliente = new javax.swing.JLabel();
        jPainelCamada1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListaCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 470, -1));

        jButtonExcluir.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir Cliente");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 180, -1));

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 470, 40));

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Exclusão de Clientes");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, 470));

        jLabelFundoExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Telas/excluir-cliente.png"))); // NOI18N
        getContentPane().add(jLabelFundoExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        javax.swing.GroupLayout jPainelCamada1Layout = new javax.swing.GroupLayout(jPainelCamada1);
        jPainelCamada1.setLayout(jPainelCamada1Layout);
        jPainelCamada1Layout.setHorizontalGroup(
            jPainelCamada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPainelCamada1Layout.setVerticalGroup(
            jPainelCamada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPainelCamada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        jListaCliente.setVisible(false);
        enter = 1;
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        if(enter == 0) {
          retornaPesquisa();
        }else{
            enter = 1;
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void jListaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaClienteMouseClicked
       //retornaPesquisa();
       jListaCliente.setVisible(true);
    }//GEN-LAST:event_jListaClienteMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ExcluirCliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ExcluirCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabelFundoExcluirCliente;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListaCliente;
    private javax.swing.JLayeredPane jPainelCamada1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

   
    public void retornaPesquisa() {
        
        List<String> c = service.listaClientes();
        
        modelo.removeAllElements();
        if(!c.isEmpty()){
            jListaCliente.setVisible(true);
            jListaCliente.setModel(modelo);
            for (String cliente : c) {
                modelo.addElement(cliente);
            }
            
        }else{
            System.out.println("Ocorreu um erro na classe Excluir Cliente");
            jListaCliente.setVisible(false);
        }
    }
    
    public void excluir() {
        // Verifica se há algum elemento selecionado na JList
        int index = jListaCliente.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para excluir.");
        }else{

        // Recupera o cliente selecionado na JList
        String clienteSelecionado = jListaCliente.getSelectedValue();

            System.out.println(index);
            System.out.println(clienteSelecionado);

        // Exemplo de como excluir usando o serviço de cliente:
        
        service.excluirCliente(clienteSelecionado);
        retornaPesquisa();
        }
    }

    public ClienteService getService() {
        return service;
    }

    public void setService(ClienteService service) {
        this.service = service;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    public void setTxtPesquisa(JTextField txtPesquisa) {
        this.txtPesquisa = txtPesquisa;
    }
}
