package br.com.barbershop.view.servicos;

import br.com.barbershop.controller.ServiceController;

/**
 *
 * @author jefferson.silva
 */
public class EscolhaService extends javax.swing.JFrame {
    
    private final ServiceController controller;
    
    /**
     * Creates new form EscolhaService
     */
    public EscolhaService() {
        initComponents();
        this.controller =  new ServiceController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExcluirServico = new javax.swing.JButton();
        jButtonAtualizarServico = new javax.swing.JButton();
        jButtonCadastrarServico = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExcluirServico.setText("Excluir Serviço Existente");
        jButtonExcluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));

        jButtonAtualizarServico.setText("Atualizar Serviço Existente");
        jButtonAtualizarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jButtonCadastrarServico.setText("Cadastrar Novo Serviço");
        jButtonCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("O que você deseja fazer?");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabelPlanoDeFundo.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPlanoDeFundo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPlanoDeFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\jefferson.silva\\Documents\\GitHub\\Sistema-Barbearia-BarberShop\\BarberShop\\src\\main\\java\\resources\\Telas\\duvida.png")); // NOI18N
        getContentPane().add(jLabelPlanoDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 430, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarServicoActionPerformed
        this.controller.navegarParaAtualizarServico();
    }//GEN-LAST:event_jButtonAtualizarServicoActionPerformed

    private void jButtonCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarServicoActionPerformed
        this.controller.navegarParaCadastrarServico();
    }//GEN-LAST:event_jButtonCadastrarServicoActionPerformed

    private void jButtonExcluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirServicoActionPerformed
        this.controller.navegarParaExcluirServico();
    }//GEN-LAST:event_jButtonExcluirServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(EscolhaService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarServico;
    private javax.swing.JButton jButtonCadastrarServico;
    private javax.swing.JButton jButtonExcluirServico;
    private javax.swing.JLabel jLabelPlanoDeFundo;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
